# Settings required for cron/version checking actions of the library version.
interval_days: 14
swipebox_last_check: 0
# The local version, detected in the libraries directory.
swipebox_local_version: 0
# The vendor version, detected on last succesful cron action.
swipebox_checked_version: 0
