dsbox.settings:
    type: mapping
    label: 'Dsbox settings'
    mapping:
        interval_days:
            type: integer
            label: 'Interval days'
        swipebox_last_check:
            type: boolean
            label: 'Swipebox last check'
        swipebox_local_version:
            type: boolean
            label: 'Swipebox local version'
        swipebox_checked_version:
            type: boolean
            label: 'Swipebox checked version'

entity_view_display.field.dsbox_link:
  type: entity_field_view_display_base
  label: 'Link format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
          trim_length:
            type: integer
            label: 'Trim link text length'
          link_gallery:
            type: string
            label: Video grouping
          link_gallery_custom:
            type: string
            label: Custom video grouping

entity_form_display.field.dsbox_link_default:
  type: entity_field_form_display_base
  label: 'Link format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        placeholder_url:
          type: string
          label: 'Placeholder for URL'
        placeholder_title:
          type: label
          label: 'Placeholder for link text'
          